name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test and lint:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1

    - name: Run tests
      run: go test ./...

    - name: GolangCI-Lint
      uses: golangci/golangci-lint-action@v2
  deploy:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .
        docker push ghcr.io/${{ github.repository }}:latest
    
    - name: Trigger Updater
      run: |
        curl -X POST -d '{"task":"deploy-back", "secret":"${{ secrets.UPDATER_SECRET }}"}' https://YOUR_DROPLET_IP_OR_DOMAIN/update
    